---

- name: Delete resource group
  azure_rm_resourcegroup:
    name: "{{ cloud_vpn_name }}-responder-resource-group"
    location: "{{ cloud_vpn_responder_azure_region }}"
    subscription_id: "{{ cloud_vpn_responder_azure_subscription_id }}"
    tenant: "{{ cloud_vpn_responder_azure_tenant }}"
    client_id: "{{ cloud_vpn_responder_azure_client_id }}"
    secret: "{{ cloud_vpn_responder_azure_secret }}"
    force: True
    state: absent
