---

- name: Create responder resource group
  azure_rm_resourcegroup:
    name: "{{ cloud_vpn_name }}-responder-resource-group"
    location: "{{ cloud_vpn_responder_azure_region }}"
    subscription_id: "{{ cloud_vpn_responder_azure_subscription_id }}"
    tenant: "{{ cloud_vpn_responder_azure_tenant }}"
    client_id: "{{ cloud_vpn_responder_azure_client_id }}"
    secret: "{{ cloud_vpn_responder_azure_secret }}"

- name: Create Azure responder provision stack
  azure_rm_deployment:
    resource_group: "{{ cloud_vpn_name }}-responder-resource-group"
    location: "{{ cloud_vpn_responder_azure_region }}"
    deployment_name: "{{ cloud_vpn_name }}-responder-provision-template"
    template: "{{ lookup('template', 'templates/cloud_vpn/provisioners/azure_vpn/responder/provision.j2') }}"
    subscription_id: "{{ cloud_vpn_responder_azure_subscription_id }}"
    tenant: "{{ cloud_vpn_responder_azure_tenant }}"
    client_id: "{{ cloud_vpn_responder_azure_client_id }}"
    secret: "{{ cloud_vpn_responder_azure_secret }}"
    parameters:
      virtualNetworkName: 
        value: "{{ cloud_vpn_name }}-virtual-network"
      azureVNetAddressPrefix: 
        value: "{{ cloud_vpn_responder_vpc_cidr }}"
      subnetName: 
        value: Subnet1
      subnetPrefix: 
        value: "{{ cloud_vpn_responder_cidr }}"
      gatewaySubnetPrefix: 
        value: "{{ cloud_vpn_responder_azure_gateway_subnet_cidr }}"

- name: Set cloud_vpn_responder_vpc_id
  set_fact:
    cloud_vpn_responder_vpc_id: "{{ cloud_vpn_name }}-virtual-network"
